name: Daily Reminder

on:
  schedule:
    - cron: "39 15 * * *" # 台北時間 23:59 執行 (發現不明原因會晚20分鐘執行，所以設定UTC時間15:39)
  workflow_dispatch: # 新增手動觸發功能

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call Spending Track API
        run: |
          curl -v -X GET "http://spending-track.infinityfreeapp.com/api/reminder.php"
