name: Daily Reminder

on:
  schedule:
    # 每天晚上 15:59 (台北時間23:59)
    - cron: "20 04 * * *"

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      # 使用 curl 發送 HTTP 請求到指定 API
      - name: Call API
        run: |
          curl -X GET "http://spending-track.infinityfreeapp.com/api/reminder.php"
